# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/leilinfei/Desktop/ApproximateValueIterationForDPDP-MP-TW

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/leilinfei/Desktop/ApproximateValueIterationForDPDP-MP-TW

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/leilinfei/Desktop/ApproximateValueIterationForDPDP-MP-TW/CMakeFiles /Users/leilinfei/Desktop/ApproximateValueIterationForDPDP-MP-TW/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/leilinfei/Desktop/ApproximateValueIterationForDPDP-MP-TW/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named adp

# Build rule for target.
adp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adp
.PHONY : adp

# fast build rule for target.
adp/fast:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/build
.PHONY : adp/fast

avi.o: avi.cpp.o

.PHONY : avi.o

# target to build an object file
avi.cpp.o:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/avi.cpp.o
.PHONY : avi.cpp.o

avi.i: avi.cpp.i

.PHONY : avi.i

# target to preprocess a source file
avi.cpp.i:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/avi.cpp.i
.PHONY : avi.cpp.i

avi.s: avi.cpp.s

.PHONY : avi.s

# target to generate assembly for a file
avi.cpp.s:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/avi.cpp.s
.PHONY : avi.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/main.cpp.s
.PHONY : main.cpp.s

mdp.o: mdp.cpp.o

.PHONY : mdp.o

# target to build an object file
mdp.cpp.o:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/mdp.cpp.o
.PHONY : mdp.cpp.o

mdp.i: mdp.cpp.i

.PHONY : mdp.i

# target to preprocess a source file
mdp.cpp.i:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/mdp.cpp.i
.PHONY : mdp.cpp.i

mdp.s: mdp.cpp.s

.PHONY : mdp.s

# target to generate assembly for a file
mdp.cpp.s:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/mdp.cpp.s
.PHONY : mdp.cpp.s

route.o: route.cpp.o

.PHONY : route.o

# target to build an object file
route.cpp.o:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/route.cpp.o
.PHONY : route.cpp.o

route.i: route.cpp.i

.PHONY : route.i

# target to preprocess a source file
route.cpp.i:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/route.cpp.i
.PHONY : route.cpp.i

route.s: route.cpp.s

.PHONY : route.s

# target to generate assembly for a file
route.cpp.s:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/route.cpp.s
.PHONY : route.cpp.s

solution.o: solution.cpp.o

.PHONY : solution.o

# target to build an object file
solution.cpp.o:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/solution.cpp.o
.PHONY : solution.cpp.o

solution.i: solution.cpp.i

.PHONY : solution.i

# target to preprocess a source file
solution.cpp.i:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/solution.cpp.i
.PHONY : solution.cpp.i

solution.s: solution.cpp.s

.PHONY : solution.s

# target to generate assembly for a file
solution.cpp.s:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/solution.cpp.s
.PHONY : solution.cpp.s

solver.o: solver.cpp.o

.PHONY : solver.o

# target to build an object file
solver.cpp.o:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/solver.cpp.o
.PHONY : solver.cpp.o

solver.i: solver.cpp.i

.PHONY : solver.i

# target to preprocess a source file
solver.cpp.i:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/solver.cpp.i
.PHONY : solver.cpp.i

solver.s: solver.cpp.s

.PHONY : solver.s

# target to generate assembly for a file
solver.cpp.s:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/solver.cpp.s
.PHONY : solver.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/util.cpp.s
.PHONY : util.cpp.s

vfa.o: vfa.cpp.o

.PHONY : vfa.o

# target to build an object file
vfa.cpp.o:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/vfa.cpp.o
.PHONY : vfa.cpp.o

vfa.i: vfa.cpp.i

.PHONY : vfa.i

# target to preprocess a source file
vfa.cpp.i:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/vfa.cpp.i
.PHONY : vfa.cpp.i

vfa.s: vfa.cpp.s

.PHONY : vfa.s

# target to generate assembly for a file
vfa.cpp.s:
	$(MAKE) -f CMakeFiles/adp.dir/build.make CMakeFiles/adp.dir/vfa.cpp.s
.PHONY : vfa.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... adp"
	@echo "... avi.o"
	@echo "... avi.i"
	@echo "... avi.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mdp.o"
	@echo "... mdp.i"
	@echo "... mdp.s"
	@echo "... route.o"
	@echo "... route.i"
	@echo "... route.s"
	@echo "... solution.o"
	@echo "... solution.i"
	@echo "... solution.s"
	@echo "... solver.o"
	@echo "... solver.i"
	@echo "... solver.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... vfa.o"
	@echo "... vfa.i"
	@echo "... vfa.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

